steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mentoia-api:$COMMIT_SHA', '.']
  
  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mentoia-api:$COMMIT_SHA']
  
  # Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mentoia-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mentoia-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '600'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/mentoia-api:$COMMIT_SHA'

